export const CONNECTION_SET_DETAILS = 'CONNECTION_SET_DETAILS';
export type CONNECTION_SET_DETAILS = typeof CONNECTION_SET_DETAILS;

export const CONNECTION_SET_STATUS = 'CONNECTION_SET_STATUS';
export type CONNECTION_SET_STATUS = typeof CONNECTION_SET_STATUS;

export const CONNECTION_CLEAR_STATUS = 'CONNECTION_CLEAR_STATUS';
export type CONNECTION_CLEAR_STATUS = typeof CONNECTION_CLEAR_STATUS;

export const CONNECTION_SET_ACTIVE = 'CONNECTION_SET_ACTIVE';
export type CONNECTION_SET_ACTIVE = typeof CONNECTION_SET_ACTIVE;

export const CONNECTION_VALIDATE_FIELD = 'CONNECTION_VALIDATE_FIELD';
export type CONNECTION_VALIDATE_FIELD = typeof CONNECTION_VALIDATE_FIELD;

export const CONNECTION_INVALIDATE_FIELD = 'CONNECTION_INVALIDATE_FIELD';
export type CONNECTION_INVALIDATE_FIELD = typeof CONNECTION_INVALIDATE_FIELD;

export const CONNECTION_VALIDATE_ALL_FIELDS = 'CONNECTION_VALIDATE_ALL_FIELDS';
export type CONNECTION_VALIDATE_ALL_FIELDS = typeof CONNECTION_VALIDATE_ALL_FIELDS;